Resources:

  ZTWOAIGW:
    Type: AWS::EC2::InternetGateway

  ZTWOAVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        InstanceTenancy: default
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
        Tags:
          - Key: environment
            Value: ZTWOAVPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: 'True'
      VpcId: !Ref 'ZTWOAVPC'

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: 'True'
      VpcId: !Ref 'ZTWOAVPC'

  SARoutePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'ZTWOAVPC'

  NetworkACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'ZTWOAVPC'

  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-035be7bafff33b6b6
      InstanceType: t2.micro
      KeyName: mypubpri
      UserData: IyEvYmluL2Jhc2gKY2QgaG9tZS9lYzItdXNlcgp5dW0gdXBkYXRlIC15Cnl1bSB1cGdyYWRlCnl1bSBpbnN0YWxsIGdpdCAteQpnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL01hc25hZE5laGl0aC96ZXJvMmFyY2hpdGVjdC5naXQKY2QgemVybzJhcmNoaXRlY3QKY2Qgb25lX3VzZXIKYW1hem9uLWxpbnV4LWV4dHJhcyBpbnN0YWxsIGVwZWwgLXkKeXVtIGluc3RhbGwgLXkgbm9kZWpzIG5wbQpucG0gaW5zdGFsbCAteQpkbnNhZGRyZXNzPSQoY3VybCAtcyBodHRwOi8vMTY5LjI1NC4xNjkuMjU0L2xhdGVzdC9tZXRhLWRhdGEvcHVibGljLWhvc3RuYW1lKQpleHBvcnQgZG5zX25hbWU9JHtkbnNhZGRyZXNzfQpucG0gaW5zdGFsbCBmb3JldmVyIC1nCnN1ZG8gLXUgZWMyLXVzZXIgL3Vzci9saWIvbm9kZV9tb2R1bGVzL2ZvcmV2ZXIvYmluL2ZvcmV2ZXIgc3RhcnQgL2hvbWUvZWMyLXVzZXIvemVybzJhcmNoaXRlY3Qvb25lX3VzZXIvc2VydmVyLmpz
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref 'PublicSubnetA'
          GroupSet: [!Ref 'EC2SG']

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 SecurityGroup
      VpcId: !Ref 'ZTWOAVPC'
      SecurityGroupIngress: 
        - 
          IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  NACLEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref 'NetworkACL'

  NACLEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref 'NetworkACL'

  subnetacl1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref 'NetworkACL'
      SubnetId: !Ref 'PublicSubnetA'

  subnetacl2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref 'NetworkACL'
      SubnetId: !Ref 'PublicSubnetB'

  SAIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'ZTWOAVPC'
      InternetGatewayId: !Ref 'ZTWOAIGW'    

  subnetRoutePublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref 'SARoutePublic'
      SubnetId: !Ref 'PublicSubnetA'

  subnetRoutePublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref 'SARoutePublic'
      SubnetId: !Ref 'PublicSubnetB'

  publicroute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref 'SARoutePublic'
      GatewayId: !Ref 'ZTWOAIGW'
    DependsOn: ZTWOAIGW